context:
  version: "3.24.01"

package:
  name: cetmodules
  version: ${{ version }}

source:
  url: https://github.com/FNALssi/cetmodules/archive/refs/tags/${{ version }}.tar.gz
  sha256: 6ef8b522b02298a787a318cda898deedc250cdd336dc3168fad934ef607b5916
  patches:
    - auto-include-helpers.patch
    - namespace-install-paths.patch

build:
  noarch: generic
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - sed
  run:
    - bash
    - perl
    - python
    - __unix

tests:
  - package_contents:
      files:
        - share/cetmodules/cmake/cetmodulesConfig.cmake
        - share/cetmodules/cmake/cetmodulesConfigVersion.cmake
        - share/cetmodules/Modules/CetCMakeEnv.cmake
        - share/cetmodules/Modules/CetCMakeUtils.cmake
        - share/cetmodules/Modules/CetCMakeConfig.cmake
        - share/cetmodules/Modules/CetMake.cmake
        - libexec/cetmodules/checkClassVersion
        - libexec/cetmodules/filter-program-options
        - libexec/cetmodules/make_bash_completions

about:
  homepage: https://github.com/FNALssi/cetmodules
  summary: CMake modules for building interdependent scientific software (Fermilab)
  description: |
    cetmodules provides a set of CMake modules and helper scripts for
    building and using interdependent scientific software. It is developed
    by the Fermilab Scientific Computing Division and used as the build
    infrastructure for the art / LArSoft / Phlex ecosystem.

    Features include facilities for ROOT dictionary generation, assisted
    production of libraries and executables using modern CMake idioms,
    full-featured CMake config file generation with target import / export
    and dependency management, and easy installation of FHiCL / GDML / source
    data files.
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/FNALssi/cetmodules

extra:
  recipe-maintainers:
    - calcuttj
    - olantwin
